name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - name: Use current action
        uses: getsentry/action-eslint-fix@v1
        with:
          files: src/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
